Controllers films users
KalyghniiA/java-filmorate pull request #5
Opened 2024-01-31 11:39 UTC by KalyghniiA

2024-01-31 12:00 UTC, KalyghniiA commented
СОздание Controllers

2024-02-01 10:21 UTC, vlolad requested changes
Привет!

Очень хорошо, есть пару замечаний по задвоению аннотаций и мелкие по реализации, но очень хорошо)

Жду правок!

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    @Pattern(regexp = "^\\w+$", message = "Логин не валиден")
Неплохо!

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    @NotNull(message = "Пустое значение логина")
Лучше заменить на NotBlank

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +        if (user.getName() == null) {
Это кстати может случиться и при обновлении (метод PUT), можно сделать приватный класс и использовать его и в создании, и в обновлении

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +        if (user.getId() != null && users.containsKey(user.getId())) {
В этот метод передается новый пользователь для создания. Если у переданного объекта есть ID, то мы его перезаписываем на порядковый номер ID в сервисе

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +    public User getUser(@PathVariable("id") String id) throws UserControllerException {
id можно сразу в @PathVariable парсить в Integer спрингом из коробки, можно доработать

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +    public User getUser(@PathVariable("id") String id) throws UserControllerException {
Сейчас реализация неплохая, т.к. есть обработка ошибок без спринга, это на улучшение комментарий)

2024-02-01 10:21 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/util/Util.java
> +    public static final  LocalDate VALIDATION_DATE = LocalDate.of(1895, 12, 28);
Огонь!

2024-02-01 10:21 UTC, vlolad commented on src/test/java/ru/yandex/practicum/filmorate/ValidationTest.java
> +public class ValidationTest {
Валидация верная, молодец!

2024-02-02 13:08 UTC, vlolad approved these changes
Огонь! Принимается с:
С каждым спринтом проект будет всё интереснее

2024-03-12 17:07 UTC, merged